### PR TITLE
Add dependencies to smart.json.  [Fixes #1]

### LINKED ISSUE #1: Getting error on install
After I did an `mrt add cucumber` I got this error:

```
cucumber: updating npm dependencies -- cucumber, chokidar, zombie, disrequire...
=> Errors while scanning packages:

While building package `cucumber`:
error: no such package: 'selenium'
error: no such package: 'mirror'
```

### PR DESCRIPTION
**Pull request by queso**

### CODE REVIEW

**Comment by queso** [comment]
Does this look ok to merge @xdissent?

**Comment by xdissent** [comment]
Almost! Last night we talked about removing the protractor and selenium support that's built in and putting it in separate packages. The zombie stuff can stay as the default since it's so lightweight.

**Comment by queso** [comment]
I am fine removing it, but I am getting ready to release the cucumber chapter in the testing book and I would prefer my readers just need to `mrt add cucumber` to get started.  Right now they have to mrt add a few extra things...

**Comment by queso** [comment]
Actually, I could see removing selenium and protractor support into it's own package as being an advantage.  I am just using zombie in my chapter right now and don't really need that extra package in there.

I've updated the PR to just be mirror in the dependencies.  That will at least allow the user to `mrt add selenium` without throwing errors about two packages missing for cucumber, I think.

**Comment by xdissent** [comment]
Cool, I'll get this sorted out and release a new version to atmosphere shortly. Thanks!

**Pull request merged**
